export const Steps = Object.freeze({
  NEW: 0,
  ONBOARDING_NAME: 1,
  ONBOARDING_TRADE: 2,
  ONBOARDING_CERTIFICATE: 3,
  SKILL_EXTRACTION: 4,
  SKILL_CARD_SHOWN: 5,
  JOBS_SHOWN: 6,
  JOB_APPLIED: 7,
  INTERVIEW_Q1: 8,
  INTERVIEW_Q2: 9,
  INTERVIEW_Q3: 10,
  TRACKING: 11,
  PLACED: 12,
  UNREACHABLE: 13,
  ONBOARDING_DOCUMENTS: 14,
  AADHAAR_OTP_SENT: 15,
  LANGUAGE_SELECT: 16,
  PLACEMENT_DETAILS: 17,
  SALARY_CAPTURE: 20,
  SALARY_RETRY: 21,
  RETENTION_CHECK: 22,
  RETENTION_RETRY: 23,
  EMPLOYER_PING_REPLY: 24,
  STOPPED: 99
});

export const StepNames = Object.freeze(
  Object.fromEntries(Object.entries(Steps).map(([name, value]) => [value, name]))
);

export const EventTypes = Object.freeze({
  BUTTON_TAPPED: 'BUTTON_TAPPED',
  INTERVIEW_COMPLETED: 'INTERVIEW_COMPLETED',
  INTERVIEW_STARTED: 'INTERVIEW_STARTED',
  JOB_APPLIED: 'JOB_APPLIED',
  JOB_MATCHED: 'JOB_MATCHED',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  NUDGE_DELIVERED: 'NUDGE_DELIVERED',
  NUDGE_FAILED: 'NUDGE_FAILED',
  NUDGE_SENT: 'NUDGE_SENT',
  ONBOARDING_TRIGGERED: 'ONBOARDING_TRIGGERED',
  PING_RECEIVED: 'PING_RECEIVED',
  PING_RELAYED: 'PING_RELAYED',
  PING_SENT: 'PING_SENT',
  PLACEMENT_CONFIRMED: 'PLACEMENT_CONFIRMED',
  PLACEMENT_REPORTED: 'PLACEMENT_REPORTED',
  RETENTION_LEFT: 'RETENTION_LEFT',
  RETENTION_NO_RESPONSE: 'RETENTION_NO_RESPONSE',
  RETENTION_RETAINED: 'RETENTION_RETAINED',
  SALARY_CAPTURED: 'SALARY_CAPTURED',
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_RESUMED: 'SESSION_RESUMED',
  STEP_ADVANCED: 'STEP_ADVANCED',
  VOICE_RECEIVED: 'VOICE_RECEIVED'
});

export const PlacementStatus = Object.freeze({
  ONBOARDING: 'ONBOARDING',
  CARD_READY: 'CARD_READY',
  MATCHING: 'MATCHING',
  APPLIED: 'APPLIED',
  TRACKING: 'TRACKING',
  PLACED: 'PLACED',
  AT_RISK: 'AT_RISK',
  STOPPED: 'STOPPED'
});
