export const Steps = Object.freeze({
  NEW: 0,
  ONBOARDING_NAME: 1,
  ONBOARDING_TRADE: 2,
  ONBOARDING_CERTIFICATE: 3,
  SKILL_EXTRACTION: 4,
  SKILL_CARD_SHOWN: 5,
  JOBS_SHOWN: 6,
  JOB_APPLIED: 7,
  INTERVIEW_Q1: 8,
  INTERVIEW_Q2: 9,
  INTERVIEW_Q3: 10,
  TRACKING: 11,
  PLACED: 12,
  UNREACHABLE: 13,
  STOPPED: 99
});

export const StepNames = Object.freeze(
  Object.fromEntries(Object.entries(Steps).map(([name, value]) => [value, name]))
);

export const EventTypes = Object.freeze({
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  VOICE_RECEIVED: 'VOICE_RECEIVED',
  BUTTON_TAPPED: 'BUTTON_TAPPED',
  STEP_ADVANCED: 'STEP_ADVANCED',
  JOB_MATCHED: 'JOB_MATCHED',
  JOB_APPLIED: 'JOB_APPLIED',
  INTERVIEW_STARTED: 'INTERVIEW_STARTED',
  INTERVIEW_COMPLETED: 'INTERVIEW_COMPLETED',
  PLACEMENT_CONFIRMED: 'PLACEMENT_CONFIRMED',
  NUDGE_SENT: 'NUDGE_SENT',
  NUDGE_DELIVERED: 'NUDGE_DELIVERED',
  NUDGE_FAILED: 'NUDGE_FAILED',
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_RESUMED: 'SESSION_RESUMED'
});

export const PlacementStatus = Object.freeze({
  ONBOARDING: 'ONBOARDING',
  CARD_READY: 'CARD_READY',
  MATCHING: 'MATCHING',
  APPLIED: 'APPLIED',
  TRACKING: 'TRACKING',
  PLACED: 'PLACED',
  AT_RISK: 'AT_RISK',
  STOPPED: 'STOPPED'
});
